#ifndef HASERRORHEAD
#define HASERRORHEAD true
#define ERROR_INIT_SDL 0x00
#define ERROR_SETVIDEOMOD 0x01
#define ERROR_COPYSURFACE 0x02
#define ERROR_INIT_FONTLIB 0x03
#define ERROR_PRINTTEXT 0x04
#define ERROR_FLIPSCREEN 0x05
#define ERROR_INIT_IMGLIB 0x10
#define ERROR_LOADIMG 0x11
#define ERROR_INIT_MIXLIB 0x21
#define ERROR_LOADMUSIC 0x22
#define ERROR_LOADCHUNK 0x23
#define ERROR_PLAYMUSIC 0x24
#define ERROR_PLAYCHUNK 0x25
#endif
